- name: configure catalog

  hosts: catalog

  become: yes



  tasks:

    - name: Disable default Node.js module

      ansible.builtin.shell:

        dnf module disable nodejs -y

    

    - name: Enable nodejs 20

      ansible.builtin.command:

        dnf module enable nodejs:20 -y

    

    - name: Install nodejs

      ansible.builtin.dnf:

        name: nodejs

        state: present # This ensures it installs ONLY if missing



    - name: Create a System User  for Roboshop

      ansible.builtin.user:

        name: roboshop

        system: yes

        shell: /sbin/nolgoin

        state: present



    - name: Remove the directory if it already exists

      ansible.builtin.file:

        path: /app

        state: absent



    - name: Create a Directory

      ansible.builtin.file:

        path: /app

        state: directory

    

    - name: Download Catalog 

      ansible.builtin.get_url:

        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip

        dest: /tmp/catalog.zip



    - name: unarchieve catalog

      ansible.builtin.unarchive:

        src: /tmp/catalog.zip

        dest: /app

        remote_src: yes

    

    - name: Install Node.js dependencies

      ansible.builtin.npm:

        path: /app

        state: present



    - name: copy catalog service

      ansible.builtin.copy:

        src: catalog.service

        dest: /etc/systemd/system/catalog.service



    - name: copy mongo repo

      ansible.builtin.copy:

        src: mongo.repo

        dest: /etc/yum.repos.d/mongo.repo



    - name: install mongodb client

      ansible.builtin.dnf:

        name: mongodb-mongosh

        state: present



    - name: check products loaded

      ansible.builtin.command: 

        mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalog")'

      register: catalog_output



    - name: print the output

      ansible.builtin.debug:

        msg: "{{ catalog_output }}"

    

    - name: load the products

      ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js

      when: catalog_output.stdout  | int < 0



    - name: start catalog

      ansible.builtin.service:

        name: catalog

        state: restarted

        enabled: yes

  

    


