- name: configure rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: Cleanup old script-generated repos
    ansible.builtin.file:
      path: "/etc/yum.repos.d/{{ item }}"
      state: absent
    loop:
      - rabbitmq_erlang.repo
      - rabbitmq_rabbitmq-server.repo

  - name: copy rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo
      mode: '0644'

  - name: Force clean dnf cache
    ansible.builtin.shell: dnf clean all

  - name: install rabbitmq server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present
      update_cache: yes

  - name: start and enable rabbitmq
    ansible.builtin.service:
      state: started
      enabled: yes
      name: rabbitmq-server

  - name: create rabbitmq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop 
      password: roboshop123
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present

