- name: configure rabbitmq server

  hosts: rabbitmq

  become: yes

  tasks:

    - name: Download Erlang repository script

      ansible.builtin.get_url:

        url: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh

        dest: /tmp/erlang_repo.sh

        mode: '0744'



    - name: Run Erlang repository script

      ansible.builtin.shell: bash /tmp/erlang_repo.sh



    - name: Download RabbitMQ repository script

      ansible.builtin.get_url:

        url: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

        dest: /tmp/rabbitmq_repo.sh

        mode: '0744'



    - name: Run RabbitMQ repository script

      ansible.builtin.shell: bash /tmp/rabbitmq_repo.sh



    - name: Install RabbitMQ server

      ansible.builtin.dnf:

        name: rabbitmq-server

        state: present

        update_cache: yes



    - name: Start and enable RabbitMQ

      ansible.builtin.service:

        name: rabbitmq-server

        state: started

        enabled: yes

    - name: Create RabbitMQ user

      ansible.builtin.shell: "rabbitmqctl add_user roboshop roboshop123 || true"

      register: user_output

      changed_when: "'already exists' not in user_output.stderr"



    - name: Set RabbitMQ permissions

      ansible.builtin.shell: 'rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"'

      when: user_output is succeeded

    # - name: Create RabbitMQ user (using rabbitmqctl)

    #   ansible.builtin.shell: |

    #     rabbitmqctl add_user roboshop roboshop123 || true

    #     rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

    #   register: rabbit_user_output

    #   changed_when: "'already exists' not in rabbit_user_output.stderr"
