- name: Create EC2 instance and R53 records

  hosts: all

  connection: local



  vars:

    subnet_id: subnet-0753efad3a97c7c32

    sg_id: sg-0674ace02359e7656

    ami_id: ami-00220d79f3f480ecf5

    domain_name: intellifind.store

    env: dev

    action: create

    instances:

      - mongodb

      - catalog



  tasks:

    - name: Create EC2 Instance

      amazon.aws.ec2_instance:

        instance_type: "t3.micro"

        vpc_subnet_id: "{{ subnet_id }}"

        security_group: "{{ sg_id }}"

        image_id: "{{ ami_id }}"

        name: "{{ item }}-{{ env }}"

      loop: "{{ instances }}"

      register: ec2_output

      when: action == "create"



    - name: Print the output

      ansible.builtin.debug:

        msg: "{{ ec2_output }}"

      when: action == "create"



    - name: Create R53 records

      amazon.aws.route53:

        state: present

        zone: "{{ domain_name }}"

        record: "{{ item.item }}-{{ env }}.{{ domain_name }}"

        type: A

        ttl: 1

        value: "{{ item.instances[0].private_ip_address }}"

        wait: false

        overwrite: true

      loop: "{{ ec2_output.results}}"

      when: action == "create"



    ### DESTROY ###  

    - name: Delete R53 records

      amazon.aws.route53:

        state: absent

        zone: "{{ domain_name }}"

        record: "{{ item }}-{{ env }}.{{ domain_name }}"

        type: A

        ttl: 1

      loop: "{{ instance }}"

      when: action == "destroy"



    - name: Destroc EC2 Instance

      amazon.aws.ec2_instance:

        state: absent

        name: "{{ item }}-{{ env }}"

        wait: false

      loop: "{{ instnace }}"

      when: action == "destroy"

